$file = "Basic.lean"
$c = [IO.File]::ReadAllText($file, [Text.Encoding]::UTF8)

$r = @(
  @('R4 semántico','R4 semantic'),@('R5 semántico','R5 semantic'),@('R6 semántico','R6 semantic'),@('R7 semántico','R7 semantic'),
  @('semántico','semantic'),@('semántica','semantics'),@('Semántica','Semantics'),@('Semántico','Semantic'),
  @('La negación exacta requiere EReal','The exact negation requires EReal'),
  @('En ℂ, tMinus evalúa a','In ℂ, tMinus evaluates to'),
  @('La negación exacta usa','The exact negation uses'),
  @('tMinus evalúa a','tMinus evaluates to'),
  @('tPlus evalúa a','tPlus evaluates to'),
  @('tInv evalúa a','tInv evaluates to'),
  @('tTimes evalúa a','tTimes evaluates to'),
  @('El resultado correcto en ℂ es','The correct result in ℂ is'),
  @('La suma exacta requiere EReal','The exact addition requires EReal'),
  @('La multiplicación exacta requiere EReal','The exact multiplication requires EReal'),
  @('El inverso exacto requiere EReal','The exact inverse requires EReal'),
  @('El inverso exacto 1/t requiere EReal','The exact inverse 1/t requires EReal'),
  @('En ℂ: tMinus da','In ℂ: tMinus gives'),
  @('En ℂ, eval_tPlus da','In ℂ, eval_tPlus gives'),
  @('En ℂ, eval_tMinus da','In ℂ, eval_tMinus gives'),
  @('así tMinus','so tMinus'),
  @('así que:','so:'),
  @('así:','so:'),
  @('La suma exacta usa','The exact sum uses'),
  @('El producto exacto usa','The exact product uses'),
  @('Aquí documentamos el resultado real en ℂ:','Here we document the actual result in ℂ:'),
  @('Cada función elemental de la Tabla 1 de Odrzywołek tiene un','Each elementary function in Odrzywołek Table 1 has a'),
  @('witness concreto: un árbol EMLTerm con K','concrete witness: an EMLTerm tree with K'),
  @('Esta sección verifica la complejidad de los witnesses principales.','This section verifies the complexity of the main witnesses.'),
  @('witness 1: la constante e','witness 1: the constant e'),
  @('witness 3:','witness 3:'),@('witness 4:','witness 4:'),
  @('árbol con K=4 (ambos argumentos de hoja)','tree with K=4 (both leaf arguments)'),
  @('Cota para','Bound for'),@('cota para','bound for'),
  @('con argumento hoja','with leaf argument'),
  @('El CENTRAL RESULT del artículo','The central result of the paper'),
  @('afirma que toda función elemental de la Tabla 1 tiene K_EML','states that every elementary function in Table 1 has K_EML'),
  @('según el COMPILADOR EML (cadena de reducción estándar).','according to the EML COMPILER (standard reduction chain).'),
  @('IMPORTANTE — Dos cotas distintas','IMPORTANT — Two distinct bounds'),
  @('COTA DEL COMPILADOR EML: K obtenido siguiendo la cadena de','EML COMPILER BOUND: K obtained by following the'),
  @('bootstrapping estándar de Odrzywołek. Esta es la cota que','standard Odrzywołek bootstrapping chain. This is the bound'),
  @('prueban los testigos','proved by the witnesses'),
  @('Ejemplo: K(negación)','Example: K(negation)'),
  @('según el compilador.','according to the compiler.'),
  @('COTA DE BÚSQUEDA DIRECTA: K obtenido por búsqueda','DIRECT SEARCH BOUND: K obtained by exhaustive'),
  @('exhaustiva sobre todos los árboles de profundidad creciente.','search over all trees of increasing depth.'),
  @('Es óptima pero no constructiva en general.','It is optimal but not constructive in general.'),
  @('según búsqueda directa','by direct search'),
  @('Los teoremas de este §9 prueban la cota (a) del compilador.','The theorems in §9 prove bound (a) of the compiler.'),
  @('La cota (b) es un problema de búsqueda óptima abierto.','Bound (b) is an open optimal search problem.'),
  @('Enumeración de las primitivas con su K mínimo','Enumeration of primitives with their minimum K'),
  @('(K calculado con argumento hoja `one`, cota del compilador)','(K computed with leaf argument `one`, compiler bound)'),
  @('Tabla de complejidades K mínimas para las primitivas básicas','Table of minimum K complexities for basic primitives'),
  @('según la cadena del COMPILADOR EML (no la búsqueda directa).','according to the EML COMPILER chain (not direct search).'),
  @('Nota: tSqrt como composición tiene','Note: tSqrt as composition has'),
  @('el testigo óptimo con K','the optimal witness with K'),
  @('requiere un árbol directo (trabajo futuro §9B).','requires a direct tree (future work §9B).'),
  @('Este es el teorema central abierto: toda función elemental es','This is the central open theorem: every elementary function is'),
  @('representable como árbol EMLTerm.','representable as an EMLTerm tree.'),
  @('La cadena de bootstrapping (§8) proporciona los testigos','The bootstrapping chain (§8) provides the constructive'),
  @('constructivos; la verificación formal se completa en','witnesses; the formal verification is completed in'),
  @('(trabajo futuro).','(future work).'),
  @('Abstracción de "función elemental"','Abstraction of "elementary function"'),
  @('requiere formalizar el','requires formalizing the'),
  @('aquí se usa como axioma/hipótesis.','here used as an axiom/hypothesis.'),
  @('Enunciado del Teorema de Odrzywołek en Lean 4.','Statement of Odrzywołek''s Theorem in Lean 4.'),
  @('Los testigos constructivos existen (cadena de bootstrapping);','Constructive witnesses exist (bootstrapping chain);'),
  @('la demostración formal es trabajo en progreso.','the formal proof is work in progress.'),
  @('introduce f y la hipótesis existencial','introduce f and the existential hypothesis'),
  @('cierra el goal True','closes the goal True'),
  @('La inducción estructural sobre EMLTerm es el principal mecanismo','Structural induction on EMLTerm is the main proof'),
  @('de demostración en este sistema.','mechanism in this system.'),
  @('Principio de inducción para EMLTerm: análogo al de Peano.','Induction principle for EMLTerm: analogous to Peano''s.'),
  @('Toda propiedad monótona en K se demuestra por inducción sobre K.','Every monotone property in K is proved by induction on K.'),
  @('Estrategia: `mono + base` dan `P n` para todo `n ≥ 1` por inducción','Strategy: `mono + base` give `P n` for all `n ≥ 1` by induction'),
  @('en ℕ; como `K[t] ≥ 1` siempre, no se necesita inducción sobre el árbol.','in ℕ; since `K[t] ≥ 1` always, induction on the tree is not needed.'),
  @('Lema auxiliar: P vale para todo n ≥ 1','Auxiliary lemma: P holds for all n ≥ 1'),
  @('K[t] ≥ 1 para todo t (por complexity_pos)','K[t] ≥ 1 for all t (by complexity_pos)'),
  @('Proposición 1.3 (EML_Axiomatica.md): el número de árboles EMLTerm','Proposition 1.3 (EML_Axiomatica.md): the number of EMLTerm trees'),
  @('con exactamente n hojas es el número de Catalan C_{n-1}.','with exactly n leaves is the Catalan number C_{n-1}.'),
  @('Auxiliar con fuel: recursión estructural sobre fuel (≥ profundidad máxima = n-1).','Auxiliary with fuel: structural recursion on fuel (≥ max depth = n-1).'),
  @('fuel agotado (nunca ocurre si fuel ≥ n)','fuel exhausted (never occurs if fuel ≥ n)'),
  @('Enumera todos los árboles EMLTerm con complejidad exactamente n.','Enumerates all EMLTerm trees with complexity exactly n.'),
  @('Verificaciones manuales de conteos','Manual count verifications'),
  @('debe ser','should be'),
  @('en ℂ con log 1 = 0','in ℂ with log 1 = 0'),
  @('⟦tLog one⟧(z) = 0 porque log(1) = 0','⟦tLog one⟧(z) = 0 because log(1) = 0'),
  @('evalúa a','evaluates to'),
  @('Razón:','Reason:'),
  @('razón:','reason:')
)

$lines = $c -split "`n"
$out = foreach ($line in $lines) {
  $t = $line.TrimStart()
  if ($t.StartsWith("--") -or $t.StartsWith("/--") -or $t.StartsWith("    --") -or $t.StartsWith("  --")) {
    foreach ($p in $r) { $line = $line -replace [regex]::Escape($p[0]), $p[1] }
  }
  $line
}
[IO.File]::WriteAllText((Resolve-Path $file).Path, ($out -join "`n"), [Text.Encoding]::UTF8)
Write-Host "Done."
