$dir = $PSScriptRoot
$files = Get-ChildItem $dir -Filter "*.lean"

$pairs = @(
  @("Formalización del", "Formalization of the"),
  @("Formalización", "Formalization"),
  @("formaliza la estructura", "formalizes the structure"),
  @("formaliza", "formalizes"),
  @("genera todas las funciones elementales", "generates all elementary functions"),
  @("Fuente:", "Source:"),
  @("Proyecto:", "Project:"),
  @("Licenciatura en Matemáticas", "Mathematics Undergraduate Programme"),
  @("CONTENIDO", "CONTENTS"),
  @("RESUMEN", "SUMMARY"),
  @("Gramática de términos EML", "EML term grammar"),
  @("Complejidad K \(número de hojas\)", "Complexity K (leaf count)"),
  @("Complejidad K", "Complexity K"),
  @("número de hojas", "leaf count"),
  @("Número de hojas", "Leaf count"),
  @("Definiciones intermedias", "Auxiliary definitions"),
  @("Árboles testigo", "Witness trees"),
  @("árbol testigo", "witness tree"),
  @("Árbol testigo", "Witness tree"),
  @("testigos", "witnesses"),
  @("testigo", "witness"),
  @("Terminación de TRS", "TRS termination"),
  @("Terminación", "Termination"),
  @("terminación", "termination"),
  @("terminante", "terminating"),
  @("Confluencia de TRS", "TRS confluence"),
  @("Confluencia", "Confluence"),
  @("confluente", "confluent"),
  @("confluencia", "confluence"),
  @("Evaluación semántica sobre", "Semantic evaluation over"),
  @("Evaluación semántica", "Semantic evaluation"),
  @("evaluación semántica", "semantic evaluation"),
  @("Evaluación", "Evaluation"),
  @("evaluación", "evaluation"),
  @("cadena de bootstrapping", "bootstrapping chain"),
  @("Cota K", "K bound"),
  @("Teorema de completitud", "Completeness theorem"),
  @("Torre de Liouville como Tipo Inductivo", "Liouville Tower as an Inductive Type"),
  @("Torre de Liouville", "Liouville Tower"),
  @("torre de Liouville", "Liouville tower"),
  @("Torre inductiva", "Inductive tower"),
  @("Torre base", "Base tower"),
  @("TIPO DE EXTENSIONES PERMITIDAS", "PERMITTED EXTENSION TYPES"),
  @("tipos de extensiones elementales", "three types of elementary extensions"),
  @("Extensión algebraica", "Algebraic extension"),
  @("Extensión exponencial", "Exponential extension"),
  @("Extensión logarítmica", "Logarithmic extension"),
  @("NIVEL MÍNIMO DE CADA FUNCIÓN", "MINIMUM LEVEL FOR EACH FUNCTION"),
  @("nivel mínimo", "minimum level"),
  @("CORRESPONDENCIA", "CORRESPONDENCE"),
  @("correspondencia", "correspondence"),
  @("Correspondencia", "Correspondence"),
  @("OPERACIONES DE CAMPO DENTRO DE LA TORRE", "FIELD OPERATIONS WITHIN THE TOWER"),
  @("campo elemental", "elementary field"),
  @("RELACIÓN DE EXTENSIÓN", "EXTENSION RELATION"),
  @("relación de extensión", "extension relation"),
  @("es reflexiva", "is reflexive"),
  @("es transitiva", "is transitive"),
  @("Reflexividad", "Reflexivity"),
  @("ESTADO ACTUAL", "CURRENT STATUS"),
  @("Estado actual", "Current status"),
  @("trabajo futuro", "future work"),
  @("Trabajo futuro", "Future work"),
  @("OBSTRUCCIÓN DEL IDEAL DIAGONAL", "DIAGONAL IDEAL OBSTRUCTION"),
  @("OBSTRUCCIÓN DE CAMPO DE HARDY", "HARDY FIELD OBSTRUCTION"),
  @("Obstrucción del Ideal Diagonal", "Diagonal Ideal Obstruction"),
  @("Obstrucción del Campo de Hardy", "Hardy Field Obstruction"),
  @("obstrucción", "obstruction"),
  @("Obstrucción", "Obstruction"),
  @("OBSTRUCCIONES ANALÍTICAS", "ANALYTIC OBSTRUCTIONS"),
  @("axioms honestos", "honest axioms"),
  @("axiom honesto", "honest axiom"),
  @("VERIFICACIÓN DE TIPOS", "TYPE CHECKING"),
  @("documentación interna", "internal documentation"),
  @("Verificación", "Verification"),
  @("verificación", "verification"),
  @("VERIFICADAS", "VERIFIED"),
  @("VERIFICADOS", "VERIFIED"),
  @("Álgebra Universal del Operador Sheffer-EML", "Universal Algebra of the Sheffer-EML Operator"),
  @("RESULTADO CENTRAL", "CENTRAL RESULT"),
  @("CONTENIDO", "CONTENTS"),
  @("Typeclass ShefferOperator", "ShefferOperator typeclass"),
  @("TYPECLASS", "TYPECLASS"),
  @("Notación local", "Local notation"),
  @("GRUPO ABELIANO DERIVADO", "DERIVED ABELIAN GROUP"),
  @("grupo abeliano", "abelian group"),
  @("Grupo abeliano", "Abelian group"),
  @("Suma del grupo subyacente", "Underlying group addition"),
  @("Inverso derivado", "Derived inverse"),
  @("INSTANCIA: EML COMO ShefferOperator", "INSTANCE: EML AS ShefferOperator"),
  @("INSTANCIA EDL", "EDL INSTANCE"),
  @("Instancia EDL", "EDL instance"),
  @("OBSERVACIÓN IMPORTANTE", "IMPORTANT REMARK"),
  @("OBSERVACIÓN MATEMÁTICA IMPORTANTE", "IMPORTANT MATHEMATICAL REMARK"),
  @("tipo envolvente", "wrapper type"),
  @("Tipo envolvente", "Wrapper type"),
  @("isomorfismo", "isomorphism"),
  @("ISOMORFISMO", "ISOMORPHISM"),
  @("Isomorfismo", "Isomorphism"),
  @("OPERADOR EDL COMPLEJO", "COMPLEX EDL OPERATOR"),
  @("argumentos intercambiados", "swapped arguments"),
  @("UNIVERSALIDAD", "UNIVERSALITY"),
  @("profundidad", "depth"),
  @("Profundidad", "Depth"),
  @("MOTIVACIÓN", "MOTIVATION"),
  @("DESCUBRIMIENTO CENTRAL", "CENTRAL DISCOVERY"),
  @("DIFICULTAD TÉCNICA", "TECHNICAL DIFFICULTY"),
  @("Evaluador EML sobre reales extendidos", "EML evaluator over extended reals"),
  @("EVALUACIÓN SEMÁNTICA", "SEMANTIC EVALUATION"),
  @("regla arquitectónica", "architectural rule"),
  @("REGLA ARQUITECTÓNICA", "ARCHITECTURAL RULE"),
  @("Regla arquitectónica", "Architectural rule"),
  @("Consecuencia", "Consequence"),
  @("CONSECUENCIA", "CONSEQUENCE"),
  @("Razón", "Reason"),
  @("Derivación", "Derivation"),
  @("derivación", "derivation"),
  @("demostración", "proof"),
  @("Demostración", "Proof"),
  @("prueba", "proof"),
  @("Prueba", "Proof"),
  @("enunciado", "statement"),
  @("Enunciado", "Statement"),
  @("pendiente", "pending"),
  @("Pendiente", "Pending"),
  @("conjetura", "conjecture"),
  @("Conjetura", "Conjecture"),
  @("cerradura", "closure"),
  @("Cerradura", "Closure"),
  @("cerrado", "closed"),
  @("Cerrado", "Closed"),
  @("invariante del proyecto", "project invariant"),
  @("LIMITACIÓN ARQUITECTÓNICA DOCUMENTADA", "DOCUMENTED ARCHITECTURAL LIMITATION"),
  @("Punto de entrada", "Entry point"),
  @("Reexporta", "Re-exports"),
  @("todos los módulos", "all modules")
)

foreach ($file in $files) {
  $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
  $lines = $content -split "`n"
  $newLines = foreach ($line in $lines) {
    $trimmed = $line.TrimStart()
    if ($trimmed.StartsWith("--") -or $trimmed.StartsWith("/--") -or $trimmed.StartsWith("    --")) {
      foreach ($pair in $pairs) {
        $line = $line -replace [regex]::Escape($pair[0]), $pair[1]
      }
    }
    $line
  }
  $result = $newLines -join "`n"
  [System.IO.File]::WriteAllText($file.FullName, $result, [System.Text.Encoding]::UTF8)
  Write-Host "Done: $($file.Name)"
}
Write-Host "All files translated."
